name: .NET Core

on:
  pull_request:
    branches: [ master, dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Clean dotnet
      run: dotnet clean --configuration Release
      working-directory: Source
    - name: Install dependencies
      run: dotnet restore
      working-directory: Source
    - name: Build
      run: dotnet build /nodeReuse:false --configuration Release
      working-directory: Source
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      working-directory: Source
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v1.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
