# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - iwentys

on:
  push:
    branches:
      - master
      - frontend-ci

jobs:
  build-and-deploy:
    runs-on: windows-latest
    env:
      working-directory: ./Source
      NODE_VERSION: "10.x"

    steps:
    - uses: actions/checkout@master

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.102'

    - name: Use Node.js 
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Build with dotnet
      run: dotnet build --configuration Release
      working-directory: ${{env.working-directory}}

    - name: dotnet publish
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp
      working-directory: ${{env.working-directory}}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v1
      with:
        app-name: 'iwentys'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_a2aad1ea5cc8491993076769528bbb5e }}
        package: ${{env.DOTNET_ROOT}}/myapp 
